### PR TITLE
Gracefully handle crashed / cancelled txns

### PR DESCRIPTION
**Pull request by NHDaly**
Fixes https://github.com/RelationalAI/rai-sdk-issues/issues/70 for the Julia SDK.

We currently throw a 404 error if the transaction is cancelled or crashes before executing. This will be fixed in future versions of relationalai infra, but in the meantime, this workaround swallows such errors.

### CODE REVIEW

**Comment by NHDaly** [comment]
Assuming the tests pass, I'm going to merge this without review, to unblock the benchmarking issue that originally surfaced this error.

**Comment by NHDaly** [comment]
... this didn't seem to help locally. I'll have another look tomorrow, but on reflection this can probably wait for review. Sorry I was rushing 😊

**Comment by NHDaly** [comment]
Feel free to merge yourself if you give an approval tomorrow morning!

**Review by vilterp — APPROVED** [review]

**Review by ary — APPROVED** [review]

**Comment by NHDaly** [comment]
Thanks everyone. I think i've figured out why this wasn't working. it was throwing a TaskFailedException because of the `@spawn`s, which i wasn't accounting for. I've addressed this via https://github.com/NHDaly/ExceptionUnwrapping.jl. :/

And now i've added a test, which confirms that this is finally fixed (that's how i confirmed it wasn't working).

**Review by NRHelmi — APPROVED** [review]
thanks @NHDaly

**Pull request merged**
